# Generated by Django 2.1.4 on 2019-01-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desks',
            name='executor',
            field=models.CharField(blank=True, default='', help_text='User executor', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_password',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='enabled_company',
            field=models.ManyToManyField(blank=True, help_text='access to company data', to='todo.CompanyName'),
        ),
    ]
