# Generated by Django 2.1.4 on 2019-01-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190115_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyname',
            name='name',
            field=models.TextField(help_text='RGD, Aeroflot, Rosneft, Gazprom', max_length=200),
        ),
    ]
