# Generated by Django 2.1.4 on 2019-01-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20190115_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_company',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
