# Generated by Django 2.1.4 on 2019-01-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20190116_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='enabled_company',
            field=models.ManyToManyField(blank=True, help_text='access to company data', related_name='companies', to='todo.CompanyName'),
        ),
    ]
