# Generated by Django 2.1.4 on 2019-01-16 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20190116_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_password',
            new_name='date_idsession',
        ),
    ]
