# Generated by Django 2.1.4 on 2019-01-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20190116_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desks',
            name='executor',
            field=models.CharField(default='', help_text='User executor', max_length=50),
        ),
    ]
