# Generated by Django 2.1.4 on 2019-01-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20190117_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desks',
            name='executor',
            field=models.CharField(blank=True, help_text='User executor', max_length=50, null=True),
        ),
    ]
